import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#fff" },
  input: {
    marginTop: 50,
    marginHorizontal: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    fontSize: 16,
    backgroundColor: "#f9f9f9",
  },
  filterButton: {
    margin: 12,
    padding: 10,
    backgroundColor: "#6e57c5",
    borderRadius: 8,
    alignItems: "center",
  },
  loading: { textAlign: "center", marginTop: 20, fontSize: 16 },
  map: { height: 200, margin: 12, borderRadius: 8 },
  list: { paddingBottom: 50 },
  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fafafa",
    marginHorizontal: 12,
    marginVertical: 6,
    padding: 10,
    borderRadius: 8,
    elevation: 1,
  },
  cardSelected: { borderWidth: 2, borderColor: "#6e57c5" },
  photo: { width: 60, height: 60, borderRadius: 6, marginRight: 10 },
  title: { fontSize: 16, fontWeight: "600", marginBottom: 2 },
  rating: { fontSize: 14, color: "#444" },
  distance: { fontSize: 12, color: "#666" },
  actionButton: {
    marginTop: 6,
    marginRight: 6,
    paddingVertical: 4,
    paddingHorizontal: 8,
    backgroundColor: "#6e57c5",
    borderRadius: 4,
    alignSelf: "flex-start",
  },
  actionButtonText: { color: "#fff", fontWeight: "600" },
  empty: { textAlign: "center", marginTop: 20, fontSize: 16, color: "#777" },
  modalContainer: { flex: 1, justifyContent: "center", backgroundColor: "rgba(0,0,0,0.3)" },
  modalContent: { backgroundColor: "#fff", margin: 20, borderRadius: 8, padding: 16 },
  typeButton: {
    padding: 6,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    margin: 4,
  },
  typeButtonSelected: { backgroundColor: "#6e57c5", borderColor: "#6e57c5" },
  ratingButton: {
    padding: 6,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    margin: 4,
  },
  ratingButtonSelected: { backgroundColor: "#6e57c5", borderColor: "#6e57c5" },
  distanceButton: {
    padding: 6,
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    margin: 4,
  },
  distanceButtonSelected: { backgroundColor: "#6e57c5", borderColor: "#6e57c5" },
});

export default styles;